version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cr.selcloud.ru/alobusiness/dubl-app:latest
    container_name: avito-app-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - dubl-app-net

networks:
  dubl-app-net:
    driver: bridge